services:
  # Servicio principal (Node.js)
  app:
    build:
      context: .
      target: ${STAGE}  # Cambiar a 'prod' para producción
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - node-modules-app:/app/node_modules
      #- /app/node_modules Esto es para hacer el volumen anonimo
    environment:
      - NODE_ENV=${NODE_STAGE}  # Cambiar a 'production' para prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - db-project
    # Para producción, descomenta:
    # command: ["node", "src/app.js"]

  # Base de datos PostgreSQL
  db-project:
    image: postgres:13.21-alpine3.20
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    #ports:
    #  - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db-node:/var/lib/postgresql/data

volumes:
  postgres-db-node:
    external: false
  node-modules-app:
    external: false